### PR TITLE
Phs-parallel

### LINKED ISSUE #42: Ptest documentation
> Throughout the documentation, you use `clist` as output and input to some functions - I'm not sure I understand what it is. Is it `list` you ment? Moreover, you're using various ways to describe output of the functions. Please use only one, like in the [`dcorT_test`](https://meantrix.github.io/corrp/reference/dcorT_test.html). And apropos `dcorT_test`:
>
> - [x] it should say "data", not "A data" - data is plural
> - [x] please use `snake_case` throughout, so not `dcorT_test` but `dcor_t_test` 
> - [x] add `@return` to [ptest](https://meantrix.github.io/corrp/reference/ptest.html) documentation

 _Originally posted by @jromanowska in [#7319](https://github.com/openjournals/joss-reviews/issues/7319#issuecomment-2765289247)_

### LINKED ISSUE #43: README and Vignette
> I've been checking the examples in README and here are some points you should address:
> 
> - [x] use [lintr](https://lintr.r-lib.org/) and/or [styler](https://styler.r-lib.org/) on the code (and on the entire source code of the package)
> - [x] be consistent: either you use `corrp::` in front of each function from the package or you start the examples by loading the package (`library(corrp)`) - when getting through the README code, I couldn't run `corr_matrix` because suddenly it was without the `corrp::`
> - [x] there are many warning messages (`In (function (df, x, y, algorithm = "tree", metrics = list(regression = "MAE",  ... : There are on average only 6.4 observations in each test-set for the mpg-cyl relationship.`) when executing `corrp` on `mtcars` due to small number of observations in this dataset - please consider a dataset that's larger, e.g., [palmer penguins](https://allisonhorst.github.io/palmerpenguins/)
> - [x] perhaps add a visualization of the correlation matrix?
> 
> Further, in the [vignette](https://meantrix.github.io/corrp/articles/usage-corrp.html), please:
> 
> - [x] explain the names of the names of the columns in "Exploring the Results" 
> - [x] add explanation on how to change the default significance threshold in "Filtering Significant Correlations"
> - [x] add explanation of the results and perhaps comparison with the previous calculation in "Correlation Types"
> - [x] choose another dataset and perhaps use [{bench}](https://bench.r-lib.org/) to show that your package is efficient on large datasets, also in parallel, in "Parallel Processing"
> 
> _(do not tick off the fields, I will do that)_ 

 _Originally posted by @jromanowska in [#7319](https://github.com/openjournals/joss-reviews/issues/7319#issuecomment-2765240898)_

### PR DESCRIPTION
**Pull request by PHS-Meantrix**
# Description

Make update according with reviwers request.

- Fix documentation 
- Update parallel run with devtools::load_all if  
- Use snake_case standard
- Run_styler in whole package
- Update readme
- Update viginnetes

Closes #42, Closes #43

### CODE REVIEW

**Review by igor-siciliani — APPROVED** [review]

File: R/best_acca.R [hunk 1]
```diff
@@ -4,17 +4,18 @@
...
+#' @param maxrep \[\code{integer(1)}\]\cr maximum number of interactions
 #' without change in the clusters in the ACCA method.
-#' @param maxiter \[\code{integer(1)}]\cr maximum number
+#' @param maxiter \[\code{integer(1)}\]\cr maximum number
 #' of interactions in the ACCA method.
 #' @param ... Not used. Included for S3 method consistency.
 #'
-#' @return \[\code{list(3)}]\cr A list with:
+#' @return \[\code{list}\]\cr
+#' A list with:
```
Comment (jromanowska) [inline R/best_acca.R:18]: Please add a list here, like in the other documentation
